#java -jar weshow-account-1.0.2.jar --spring.profiles.active=alpha --server.port=8000
server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
eureka:
  instance:
  #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
                                              #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
                                              #默认90s
    lease-expiration-duration-in-seconds: 6
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 3
  client:
    serviceUrl:
      defaultZone: http://192.168.11.85:8761/eureka/

spring:
  application:
    name: spring-boot-with-erueka
